INCLUDEPATH += $$PWD
DEPENDPATH += $$PWD


HEADERS += \
    $$PWD/cmdparser.h \
    $$PWD/documentview.h \
    $$PWD/geticon.h \
    $$PWD/hunspell/affentry.hxx \
    $$PWD/hunspell/affixmgr.hxx \
    $$PWD/hunspell/atypes.hxx \
    $$PWD/hunspell/baseaffix.hxx \
    $$PWD/hunspell/csutil.hxx \
    $$PWD/hunspell/filemgr.hxx \
    $$PWD/hunspell/hashmgr.hxx \
    $$PWD/hunspell/htypes.hxx \
    $$PWD/hunspell/hunspell.h \
    $$PWD/hunspell/hunspell.hxx \
    $$PWD/hunspell/hunvisapi.h \
    $$PWD/hunspell/hunzip.hxx \
    $$PWD/hunspell/langnum.hxx \
    $$PWD/hunspell/phonet.hxx \
    $$PWD/hunspell/replist.hxx \
    $$PWD/hunspell/suggestmgr.hxx \
    $$PWD/hunspell/utf_info.hxx \
    $$PWD/hunspell/w_char.hxx \
    $$PWD/minisplitter.h \
    $$PWD/pageitem.h \
    $$PWD/pdfviewer.h \
    $$PWD/pdfviewerwidget.h \
    $$PWD/playerbutton.h \
    $$PWD/presentationview.h \
    $$PWD/qpdfbookmarkmodel.h \
    $$PWD/qpdfdocument.h \
    $$PWD/qpdfdocument_p.h \
    $$PWD/qpdfdocumentrenderoptions.h \
    $$PWD/qpdfnamespace.h \
    $$PWD/samples/image_diff_png.h \
    $$PWD/synctex_parser.h \
    $$PWD/synctex_parser_advanced.h \
    $$PWD/synctex_parser_utils.h \
    $$PWD/synctex_version.h \
    $$PWD/theme.h \
    $$PWD/third_party/bigint/BigInteger.hh \
    $$PWD/third_party/bigint/BigIntegerLibrary.hh \
    $$PWD/third_party/bigint/BigIntegerUtils.hh \
    $$PWD/third_party/bigint/BigUnsigned.hh \
    $$PWD/third_party/bigint/NumberlikeArray.hh \
    $$PWD/third_party/bigint/BigUnsignedInABase.hh \
    $$PWD/third_party/base/logging.h \
    $$PWD/third_party/base/macros.h \
    $$PWD/third_party/base/numerics/safe_conversions.h \
    $$PWD/third_party/base/numerics/safe_conversions_impl.h \
    $$PWD/third_party/base/numerics/safe_math.h \
    $$PWD/third_party/base/numerics/safe_math_impl.h \
    $$PWD/third_party/base/stl_util.h \
    $$PWD/third_party/libjpeg/cderror.h \
    $$PWD/third_party/libjpeg/cdjpeg.h \
    $$PWD/third_party/libjpeg/jchuff.h \
    $$PWD/third_party/libjpeg/jconfig.h \
    $$PWD/third_party/libjpeg/jdct.h \
    $$PWD/third_party/libjpeg/jdhuff.h \
    $$PWD/third_party/libjpeg/jerror.h \
    $$PWD/third_party/libjpeg/jinclude.h \
    $$PWD/third_party/libjpeg/jmemsys.h \
    $$PWD/third_party/libjpeg/jmorecfg.h \
    $$PWD/third_party/libjpeg/jpegint.h \
    $$PWD/third_party/libjpeg/jpeglib.h \
    $$PWD/third_party/libjpeg/jversion.h \
    $$PWD/third_party/libjpeg/transupp.h \
    $$PWD/third_party/lcms/include/lcms2.h \
    $$PWD/third_party/lcms/include/lcms2_plugin.h \
    $$PWD/third_party/agg23/agg_basics.h \
    $$PWD/third_party/agg23/agg_clip_liang_barsky.h \
    $$PWD/third_party/agg23/agg_conv_dash.h \
    $$PWD/third_party/agg23/agg_conv_stroke.h \
    $$PWD/third_party/agg23/agg_curves.h \
    $$PWD/third_party/agg23/agg_path_storage.h \
    $$PWD/third_party/agg23/agg_rasterizer_scanline_aa.h \
    $$PWD/third_party/agg23/agg_renderer_scanline.h \
    $$PWD/third_party/agg23/agg_rendering_buffer.h \
    $$PWD/third_party/agg23/agg_scanline_u.h \
    $$PWD/third_party/freetype/include/freetype/freetype.h \
    $$PWD/third_party/freetype/include/freetype/ftmm.h \
    $$PWD/third_party/freetype/include/freetype/ftotval.h \
    $$PWD/third_party/freetype/include/freetype/ftoutln.h \
    $$PWD/third_party/freetype/include/freetype/internal/ftobjs.h \
    $$PWD/third_party/freetype/include/freetype/internal/ftstream.h \
    $$PWD/third_party/freetype/include/freetype/internal/tttypes.h \
    $$PWD/third_party/freetype/include/freetype/tttables.h \
    $$PWD/third_party/freetype/include/ft2build.h \
    $$PWD/third_party/freetype/src/base/ftbase.h \
    $$PWD/third_party/freetype/src/cff/cffobjs.h \
    $$PWD/third_party/freetype/src/cff/cfftypes.h \
    $$PWD/fpdfsdk/cba_annotiterator.h \
    $$PWD/fpdfsdk/cfx_systemhandler.h \
    $$PWD/fpdfsdk/cpdfsdk_annot.h \
    $$PWD/fpdfsdk/cpdfsdk_annothandlermgr.h \
    $$PWD/fpdfsdk/cpdfsdk_annotiterator.h \
    $$PWD/fpdfsdk/cpdfsdk_baannot.h \
    $$PWD/fpdfsdk/cpdfsdk_baannothandler.h \
    $$PWD/fpdfsdk/cpdfsdk_datetime.h \
    $$PWD/fpdfsdk/cpdfsdk_formfillenvironment.h \
    $$PWD/fpdfsdk/cpdfsdk_interform.h \
    $$PWD/fpdfsdk/cpdfsdk_pageview.h \
    $$PWD/fpdfsdk/cpdfsdk_widget.h \
    $$PWD/fpdfsdk/cpdfsdk_widgethandler.h \
    $$PWD/fpdfsdk/fsdk_actionhandler.h \
    $$PWD/fpdfsdk/fsdk_pauseadapter.h \
    $$PWD/fpdfsdk/pdfsdk_fieldaction.h \
    $$PWD/public/fpdf_dataavail.h \
    $$PWD/public/fpdf_doc.h \
    $$PWD/public/fpdf_edit.h \
    $$PWD/public/fpdf_ext.h \
    $$PWD/public/fpdf_flatten.h \
    $$PWD/public/fpdf_formfill.h \
    $$PWD/public/fpdf_fwlevent.h \
    $$PWD/public/fpdf_ppo.h \
    $$PWD/public/fpdf_progressive.h \
    $$PWD/public/fpdf_save.h \
    $$PWD/public/fpdf_searchex.h \
    $$PWD/public/fpdf_sysfontinfo.h \
    $$PWD/public/fpdf_text.h \
    $$PWD/public/fpdf_transformpage.h \
    $$PWD/public/fpdfview.h \
    $$PWD/core/fdrm/crypto/fx_crypt.h \
    $$PWD/core/fpdfdoc/cline.h \
    $$PWD/core/fpdfdoc/clines.h \
    $$PWD/core/fpdfdoc/cpdf_aaction.h \
    $$PWD/core/fpdfdoc/cpdf_action.h \
    $$PWD/core/fpdfdoc/cpdf_actionfields.h \
    $$PWD/core/fpdfdoc/cpdf_annot.h \
    $$PWD/core/fpdfdoc/cpdf_annotlist.h \
    $$PWD/core/fpdfdoc/cpdf_apsettings.h \
    $$PWD/core/fpdfdoc/cpdf_bookmark.h \
    $$PWD/core/fpdfdoc/cpdf_bookmarktree.h \
    $$PWD/core/fpdfdoc/cpdf_defaultappearance.h \
    $$PWD/core/fpdfdoc/cpdf_dest.h \
    $$PWD/core/fpdfdoc/cpdf_docjsactions.h \
    $$PWD/core/fpdfdoc/cpdf_filespec.h \
    $$PWD/core/fpdfdoc/cpdf_formcontrol.h \
    $$PWD/core/fpdfdoc/cpdf_formfield.h \
    $$PWD/core/fpdfdoc/cpdf_iconfit.h \
    $$PWD/core/fpdfdoc/cpdf_interform.h \
    $$PWD/core/fpdfdoc/cpdf_link.h \
    $$PWD/core/fpdfdoc/cpdf_linklist.h \
    $$PWD/core/fpdfdoc/cpdf_metadata.h \
    $$PWD/core/fpdfdoc/cpdf_nametree.h \
    $$PWD/core/fpdfdoc/cpdf_numbertree.h \
    $$PWD/core/fpdfdoc/cpdf_occontext.h \
    $$PWD/core/fpdfdoc/cpdf_pagelabel.h \
    $$PWD/core/fpdfdoc/cpdf_variabletext.h \
    $$PWD/core/fpdfdoc/cpdf_viewerpreferences.h \
    $$PWD/core/fpdfdoc/cpvt_arraytemplate.h \
    $$PWD/core/fpdfdoc/cpvt_color.h \
    $$PWD/core/fpdfdoc/cpvt_dash.h \
    $$PWD/core/fpdfdoc/cpvt_floatrect.h \
    $$PWD/core/fpdfdoc/cpvt_fontmap.h \
    $$PWD/core/fpdfdoc/cpvt_generateap.h \
    $$PWD/core/fpdfdoc/cpvt_line.h \
    $$PWD/core/fpdfdoc/cpvt_lineinfo.h \
    $$PWD/core/fpdfdoc/cpvt_secprops.h \
    $$PWD/core/fpdfdoc/cpvt_section.h \
    $$PWD/core/fpdfdoc/cpvt_sectioninfo.h \
    $$PWD/core/fpdfdoc/cpvt_word.h \
    $$PWD/core/fpdfdoc/cpvt_wordinfo.h \
    $$PWD/core/fpdfdoc/cpvt_wordplace.h \
    $$PWD/core/fpdfdoc/cpvt_wordprops.h \
    $$PWD/core/fpdfdoc/cpvt_wordrange.h \
    $$PWD/core/fpdfdoc/csection.h \
    $$PWD/core/fpdfdoc/ctypeset.h \
    $$PWD/core/fpdfdoc/fpdf_tagged.h \
    $$PWD/core/fpdfdoc/ipdf_formnotify.h \
    $$PWD/core/fpdfdoc/ipvt_fontmap.h \
    $$PWD/core/fpdfdoc/tagged_int.h \
    $$PWD/core/fpdfapi/cmaps/cmap_int.h \
    $$PWD/core/fpdfapi/cpdf_modulemgr.h \
    $$PWD/core/fpdfapi/cpdf_pagerendercontext.h \
    $$PWD/core/fpdfapi/edit/cpdf_creator.h \
    $$PWD/core/fpdfapi/edit/cpdf_pagecontentgenerator.h \
    $$PWD/core/fpdfapi/edit/editint.h \
    $$PWD/core/fpdfapi/font/cpdf_cidfont.h \
    $$PWD/core/fpdfapi/font/cpdf_font.h \
    $$PWD/core/fpdfapi/font/cpdf_fontencoding.h \
    $$PWD/core/fpdfapi/font/cpdf_simplefont.h \
    $$PWD/core/fpdfapi/font/cpdf_truetypefont.h \
    $$PWD/core/fpdfapi/font/cpdf_type1font.h \
    $$PWD/core/fpdfapi/font/cpdf_type3char.h \
    $$PWD/core/fpdfapi/font/cpdf_type3font.h \
    $$PWD/core/fpdfapi/font/font_int.h \
    $$PWD/core/fpdfapi/font/ttgsubtable.h \
    $$PWD/core/fpdfapi/page/cpdf_allstates.h \
    $$PWD/core/fpdfapi/page/cpdf_clippath.h \
    $$PWD/core/fpdfapi/page/cpdf_color.h \
    $$PWD/core/fpdfapi/page/cpdf_colorspace.h \
    $$PWD/core/fpdfapi/page/cpdf_colorstate.h \
    $$PWD/core/fpdfapi/page/cpdf_contentmark.h \
    $$PWD/core/fpdfapi/page/cpdf_contentmarkitem.h \
    $$PWD/core/fpdfapi/page/cpdf_countedobject.h \
    $$PWD/core/fpdfapi/page/cpdf_docpagedata.h \
    $$PWD/core/fpdfapi/page/cpdf_form.h \
    $$PWD/core/fpdfapi/page/cpdf_formobject.h \
    $$PWD/core/fpdfapi/page/cpdf_generalstate.h \
    $$PWD/core/fpdfapi/page/cpdf_graphicstates.h \
    $$PWD/core/fpdfapi/page/cpdf_image.h \
    $$PWD/core/fpdfapi/page/cpdf_imageobject.h \
    $$PWD/core/fpdfapi/page/cpdf_meshstream.h \
    $$PWD/core/fpdfapi/page/cpdf_page.h \
    $$PWD/core/fpdfapi/page/cpdf_pagemodule.h \
    $$PWD/core/fpdfapi/page/cpdf_pageobject.h \
    $$PWD/core/fpdfapi/page/cpdf_pageobjectholder.h \
    $$PWD/core/fpdfapi/page/cpdf_pageobjectlist.h \
    $$PWD/core/fpdfapi/page/cpdf_path.h \
    $$PWD/core/fpdfapi/page/cpdf_pathobject.h \
    $$PWD/core/fpdfapi/page/cpdf_pattern.h \
    $$PWD/core/fpdfapi/page/cpdf_shadingobject.h \
    $$PWD/core/fpdfapi/page/cpdf_shadingpattern.h \
    $$PWD/core/fpdfapi/page/cpdf_streamcontentparser.h \
    $$PWD/core/fpdfapi/page/cpdf_textobject.h \
    $$PWD/core/fpdfapi/page/cpdf_textstate.h \
    $$PWD/core/fpdfapi/page/cpdf_tilingpattern.h \
    $$PWD/core/fpdfapi/page/pageint.h \
    $$PWD/core/fpdfapi/parser/cfdf_document.h \
    $$PWD/core/fpdfapi/parser/cpdf_array.h \
    $$PWD/core/fpdfapi/parser/cpdf_boolean.h \
    $$PWD/core/fpdfapi/parser/cpdf_crypto_handler.h \
    $$PWD/core/fpdfapi/parser/cpdf_data_avail.h \
    $$PWD/core/fpdfapi/parser/cpdf_dictionary.h \
    $$PWD/core/fpdfapi/parser/cpdf_document.h \
    $$PWD/core/fpdfapi/parser/cpdf_hint_tables.h \
    $$PWD/core/fpdfapi/parser/cpdf_indirect_object_holder.h \
    $$PWD/core/fpdfapi/parser/cpdf_linearized_header.h \
    $$PWD/core/fpdfapi/parser/cpdf_name.h \
    $$PWD/core/fpdfapi/parser/cpdf_null.h \
    $$PWD/core/fpdfapi/parser/cpdf_number.h \
    $$PWD/core/fpdfapi/parser/cpdf_object.h \
    $$PWD/core/fpdfapi/parser/cpdf_parser.h \
    $$PWD/core/fpdfapi/parser/cpdf_reference.h \
    $$PWD/core/fpdfapi/parser/cpdf_security_handler.h \
    $$PWD/core/fpdfapi/parser/cpdf_simple_parser.h \
    $$PWD/core/fpdfapi/parser/cpdf_stream.h \
    $$PWD/core/fpdfapi/parser/cpdf_stream_acc.h \
    $$PWD/core/fpdfapi/parser/cpdf_string.h \
    $$PWD/core/fpdfapi/parser/cpdf_syntax_parser.h \
    $$PWD/core/fpdfapi/parser/fpdf_parser_decode.h \
    $$PWD/core/fpdfapi/parser/fpdf_parser_utility.h \
    $$PWD/core/fpdfapi/render/cpdf_docrenderdata.h \
    $$PWD/core/fpdfapi/render/cpdf_pagerendercache.h \
    $$PWD/core/fpdfapi/render/cpdf_progressiverenderer.h \
    $$PWD/core/fpdfapi/render/cpdf_rendercontext.h \
    $$PWD/core/fpdfapi/render/cpdf_renderoptions.h \
    $$PWD/core/fpdfapi/render/cpdf_textrenderer.h \
    $$PWD/core/fpdfapi/render/cpdf_type3cache.h \
    $$PWD/core/fpdfapi/render/cpdf_type3glyphs.h \
    $$PWD/core/fpdfapi/render/render_int.h \
    $$PWD/core/fpdftext/cpdf_linkextract.h \
    $$PWD/core/fpdftext/cpdf_textpage.h \
    $$PWD/core/fpdftext/cpdf_textpagefind.h \
    $$PWD/core/fpdftext/unicodenormalizationdata.h \
    $$PWD/core/fxcodec/JBig2_DocumentContext.h \
    $$PWD/core/fxcodec/codec/ccodec_basicmodule.h \
    $$PWD/core/fxcodec/codec/ccodec_faxmodule.h \
    $$PWD/core/fxcodec/codec/ccodec_flatemodule.h \
    $$PWD/core/fxcodec/codec/ccodec_iccmodule.h \
    $$PWD/core/fxcodec/codec/ccodec_jbig2module.h \
    $$PWD/core/fxcodec/codec/ccodec_jpegmodule.h \
    $$PWD/core/fxcodec/codec/ccodec_jpxmodule.h \
    $$PWD/core/fxcodec/codec/ccodec_scanlinedecoder.h \
    $$PWD/core/fxcodec/codec/codec_int.h \
    $$PWD/core/fxcodec/fx_codec.h \
    $$PWD/core/fxcodec/fx_codec_def.h \
    $$PWD/core/fxcodec/jbig2/JBig2_ArithDecoder.h \
    $$PWD/core/fxcodec/jbig2/JBig2_ArithIntDecoder.h \
    $$PWD/core/fxcodec/jbig2/JBig2_BitStream.h \
    $$PWD/core/fxcodec/jbig2/JBig2_Context.h \
    $$PWD/core/fxcodec/jbig2/JBig2_Define.h \
    $$PWD/core/fxcodec/jbig2/JBig2_GrdProc.h \
    $$PWD/core/fxcodec/jbig2/JBig2_GrrdProc.h \
    $$PWD/core/fxcodec/jbig2/JBig2_GsidProc.h \
    $$PWD/core/fxcodec/jbig2/JBig2_HtrdProc.h \
    $$PWD/core/fxcodec/jbig2/JBig2_HuffmanDecoder.h \
    $$PWD/core/fxcodec/jbig2/JBig2_HuffmanTable.h \
    $$PWD/core/fxcodec/jbig2/JBig2_HuffmanTable_Standard.h \
    $$PWD/core/fxcodec/jbig2/JBig2_Image.h \
    $$PWD/core/fxcodec/jbig2/JBig2_List.h \
    $$PWD/core/fxcodec/jbig2/JBig2_Page.h \
    $$PWD/core/fxcodec/jbig2/JBig2_PatternDict.h \
    $$PWD/core/fxcodec/jbig2/JBig2_PddProc.h \
    $$PWD/core/fxcodec/jbig2/JBig2_SddProc.h \
    $$PWD/core/fxcodec/jbig2/JBig2_Segment.h \
    $$PWD/core/fxcodec/jbig2/JBig2_SymbolDict.h \
    $$PWD/core/fxcodec/jbig2/JBig2_TrdProc.h \
    $$PWD/core/fxcrt/cfx_observable.h \
    $$PWD/core/fxcrt/cfx_retain_ptr.h \
    $$PWD/core/fxcrt/cfx_shared_copy_on_write.h \
    $$PWD/core/fxcrt/cfx_string_c_template.h \
    $$PWD/core/fxcrt/cfx_string_data_template.h \
    $$PWD/core/fxcrt/cfx_string_pool_template.h \
    $$PWD/core/fxcrt/cfx_weak_ptr.h \
    $$PWD/core/fxcrt/extension.h \
    $$PWD/core/fxcrt/fx_basic.h \
    $$PWD/core/fxcrt/fx_bidi.h \
    $$PWD/core/fxcrt/fx_coordinates.h \
    $$PWD/core/fxcrt/fx_ext.h \
    $$PWD/core/fxcrt/fx_memory.h \
    $$PWD/core/fxcrt/fx_safe_types.h \
    $$PWD/core/fxcrt/fx_stream.h \
    $$PWD/core/fxcrt/fx_string.h \
    $$PWD/core/fxcrt/fx_system.h \
    $$PWD/core/fxcrt/fx_ucd.h \
    $$PWD/core/fxcrt/fx_xml.h \
    $$PWD/core/fxcrt/fxcrt_posix.h \
    $$PWD/core/fxcrt/fxcrt_windows.h \
    $$PWD/core/fxcrt/plex.h \
    $$PWD/core/fxcrt/xml_int.h \
    $$PWD/core/fxge/cfx_facecache.h \
    $$PWD/core/fxge/cfx_fontcache.h \
    $$PWD/core/fxge/cfx_fontmapper.h \
    $$PWD/core/fxge/cfx_fontmgr.h \
    $$PWD/core/fxge/cfx_fxgedevice.h \
    $$PWD/core/fxge/cfx_gemodule.h \
    $$PWD/core/fxge/cfx_graphstate.h \
    $$PWD/core/fxge/cfx_graphstatedata.h \
    $$PWD/core/fxge/cfx_pathdata.h \
    $$PWD/core/fxge/cfx_renderdevice.h \
    $$PWD/core/fxge/cfx_substfont.h \
    $$PWD/core/fxge/cfx_unicodeencoding.h \
    $$PWD/core/fxge/cfx_windowsdevice.h \
    $$PWD/core/fxge/dib/dib_int.h \
    $$PWD/core/fxge/fontdata/chromefontdata/chromefontdata.h \
    $$PWD/core/fxge/fx_dib.h \
    $$PWD/core/fxge/fx_font.h \
    $$PWD/core/fxge/fx_freetype.h \
    $$PWD/core/fxge/ge/cfx_cliprgn.h \
    $$PWD/core/fxge/ge/cfx_folderfontinfo.h \
    $$PWD/core/fxge/ge/cttfontdesc.h \
    $$PWD/core/fxge/ge/fx_text_int.h \
    $$PWD/core/fxge/ifx_renderdevicedriver.h \
    $$PWD/core/fxge/ifx_systemfontinfo.h \
    $$PWD/core/fxge/win32/cfx_windowsdib.h \
    $$PWD/core/fxge/agg/fx_agg_driver.h \
    $$PWD/fpdfsdk/fxedit/fx_edit.h \
    $$PWD/fpdfsdk/fxedit/fxet_edit.h \
    $$PWD/fpdfsdk/fxedit/fxet_list.h \
    $$PWD/fpdfsdk/pdfwindow/PWL_Button.h \
    $$PWD/fpdfsdk/pdfwindow/PWL_Caret.h \
    $$PWD/fpdfsdk/pdfwindow/PWL_ComboBox.h \
    $$PWD/fpdfsdk/pdfwindow/PWL_Edit.h \
    $$PWD/fpdfsdk/pdfwindow/PWL_EditCtrl.h \
    $$PWD/fpdfsdk/pdfwindow/PWL_FontMap.h \
    $$PWD/fpdfsdk/pdfwindow/PWL_Icon.h \
    $$PWD/fpdfsdk/pdfwindow/PWL_ListBox.h \
    $$PWD/fpdfsdk/pdfwindow/PWL_ScrollBar.h \
    $$PWD/fpdfsdk/pdfwindow/PWL_SpecialButton.h \
    $$PWD/fpdfsdk/pdfwindow/PWL_Utils.h \
    $$PWD/fpdfsdk/pdfwindow/PWL_Wnd.h \
    $$PWD/fpdfsdk/pdfwindow/cpwl_color.h \
    $$PWD/fpdfsdk/formfiller/cba_fontmap.h \
    $$PWD/fpdfsdk/formfiller/cffl_checkbox.h \
    $$PWD/fpdfsdk/formfiller/cffl_combobox.h \
    $$PWD/fpdfsdk/formfiller/cffl_formfiller.h \
    $$PWD/fpdfsdk/formfiller/cffl_interactiveformfiller.h \
    $$PWD/fpdfsdk/formfiller/cffl_listbox.h \
    $$PWD/fpdfsdk/formfiller/cffl_pushbutton.h \
    $$PWD/fpdfsdk/formfiller/cffl_radiobutton.h \
    $$PWD/fpdfsdk/formfiller/cffl_textfield.h


SOURCES += \
    $$PWD/cmdparser.cpp \
    $$PWD/documentview.cpp \
    $$PWD/geticon.cpp \
    $$PWD/hunspell/affentry.cxx \
    $$PWD/hunspell/affixmgr.cxx \
    $$PWD/hunspell/csutil.cxx \
    $$PWD/hunspell/filemgr.cxx \
    $$PWD/hunspell/hashmgr.cxx \
    $$PWD/hunspell/hunspell.cxx \
    $$PWD/hunspell/hunzip.cxx \
    $$PWD/hunspell/phonet.cxx \
    $$PWD/hunspell/replist.cxx \
    $$PWD/hunspell/suggestmgr.cxx \
    $$PWD/minisplitter.cpp \
    $$PWD/pageitem.cpp \
    $$PWD/pdfviewer.cpp \
    $$PWD/pdfviewerwidget.cpp \
    $$PWD/playerbutton.cpp \
    $$PWD/presentationview.cpp \
    $$PWD/qpdfbookmarkmodel.cpp \
    $$PWD/qpdfdocument.cpp \
#    $$PWD/samples/image_diff.cc \
#    $$PWD/samples/image_diff_png.cc \
#    $$PWD/samples/pdfium_test.cc \
    $$PWD/synctex_parser.c \
    $$PWD/synctex_parser_utils.c \
    $$PWD/third_party/bigint/BigInteger.cc \
    $$PWD/third_party/bigint/BigIntegerUtils.cc \
    $$PWD/third_party/bigint/BigUnsigned.cc \
    $$PWD/third_party/bigint/BigUnsignedInABase.cc \
    $$PWD/third_party/libjpeg/fpdfapi_jcapimin.c \
    $$PWD/third_party/libjpeg/fpdfapi_jcapistd.c \
    $$PWD/third_party/libjpeg/fpdfapi_jccoefct.c \
    $$PWD/third_party/libjpeg/fpdfapi_jccolor.c \
    $$PWD/third_party/libjpeg/fpdfapi_jcdctmgr.c \
    $$PWD/third_party/libjpeg/fpdfapi_jchuff.c \
    $$PWD/third_party/libjpeg/fpdfapi_jcinit.c \
    $$PWD/third_party/libjpeg/fpdfapi_jcmainct.c \
    $$PWD/third_party/libjpeg/fpdfapi_jcmarker.c \
    $$PWD/third_party/libjpeg/fpdfapi_jcmaster.c \
    $$PWD/third_party/libjpeg/fpdfapi_jcomapi.c \
    $$PWD/third_party/libjpeg/fpdfapi_jcparam.c \
    $$PWD/third_party/libjpeg/fpdfapi_jcphuff.c \
    $$PWD/third_party/libjpeg/fpdfapi_jcprepct.c \
    $$PWD/third_party/libjpeg/fpdfapi_jcsample.c \
    $$PWD/third_party/libjpeg/fpdfapi_jctrans.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdapimin.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdapistd.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdcoefct.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdcolor.c \
    $$PWD/third_party/libjpeg/fpdfapi_jddctmgr.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdhuff.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdinput.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdmainct.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdmarker.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdmaster.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdmerge.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdphuff.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdpostct.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdsample.c \
    $$PWD/third_party/libjpeg/fpdfapi_jdtrans.c \
    $$PWD/third_party/libjpeg/fpdfapi_jerror.c \
    $$PWD/third_party/libjpeg/fpdfapi_jfdctfst.c \
    $$PWD/third_party/libjpeg/fpdfapi_jfdctint.c \
    $$PWD/third_party/libjpeg/fpdfapi_jidctfst.c \
    $$PWD/third_party/libjpeg/fpdfapi_jidctint.c \
    $$PWD/third_party/libjpeg/fpdfapi_jidctred.c \
    $$PWD/third_party/libjpeg/fpdfapi_jmemmgr.c \
    $$PWD/third_party/libjpeg/fpdfapi_jmemnobs.c \
    $$PWD/third_party/libjpeg/fpdfapi_jutils.c \
    $$PWD/third_party/lcms/src/cmsalpha.c \
    $$PWD/third_party/lcms/src/cmscam02.c \
    $$PWD/third_party/lcms/src/cmscgats.c \
    $$PWD/third_party/lcms/src/cmscnvrt.c \
    $$PWD/third_party/lcms/src/cmserr.c \
    $$PWD/third_party/lcms/src/cmsgamma.c \
    $$PWD/third_party/lcms/src/cmsgmt.c \
    $$PWD/third_party/lcms/src/cmshalf.c \
    $$PWD/third_party/lcms/src/cmsintrp.c \
    $$PWD/third_party/lcms/src/cmsio0.c \
    $$PWD/third_party/lcms/src/cmsio1.c \
    $$PWD/third_party/lcms/src/cmslut.c \
    $$PWD/third_party/lcms/src/cmsmd5.c \
    $$PWD/third_party/lcms/src/cmsmtrx.c \
    $$PWD/third_party/lcms/src/cmsnamed.c \
    $$PWD/third_party/lcms/src/cmsopt.c \
    $$PWD/third_party/lcms/src/cmspack.c \
    $$PWD/third_party/lcms/src/cmspcs.c \
    $$PWD/third_party/lcms/src/cmsplugin.c \
    $$PWD/third_party/lcms/src/cmsps2.c \
    $$PWD/third_party/lcms/src/cmssamp.c \
    $$PWD/third_party/lcms/src/cmssm.c \
    $$PWD/third_party/lcms/src/cmstypes.c \
    $$PWD/third_party/lcms/src/cmsvirt.c \
    $$PWD/third_party/lcms/src/cmswtpnt.c \
    $$PWD/third_party/lcms/src/cmsxform.c \
    $$PWD/third_party/libopenjpeg20/bio.c \
    $$PWD/third_party/libopenjpeg20/cio.c \
    $$PWD/third_party/libopenjpeg20/dwt.c \
    $$PWD/third_party/libopenjpeg20/event.c \
    $$PWD/third_party/libopenjpeg20/function_list.c \
    $$PWD/third_party/libopenjpeg20/image.c \
    $$PWD/third_party/libopenjpeg20/invert.c \
    $$PWD/third_party/libopenjpeg20/j2k.c \
    $$PWD/third_party/libopenjpeg20/jp2.c \
    $$PWD/third_party/libopenjpeg20/mct.c \
    $$PWD/third_party/libopenjpeg20/mqc.c \
    $$PWD/third_party/libopenjpeg20/openjpeg.c \
    $$PWD/third_party/libopenjpeg20/opj_clock.c \
    $$PWD/third_party/libopenjpeg20/pi.c \
    $$PWD/third_party/libopenjpeg20/raw.c \
    $$PWD/third_party/libopenjpeg20/t1.c \
    $$PWD/third_party/libopenjpeg20/t2.c \
    $$PWD/third_party/libopenjpeg20/tcd.c \
    $$PWD/third_party/libopenjpeg20/tgt.c \
    $$PWD/third_party/zlib_v128/adler32.c \
    $$PWD/third_party/zlib_v128/compress.c \
    $$PWD/third_party/zlib_v128/crc32.c \
    $$PWD/third_party/zlib_v128/deflate.c \
    $$PWD/third_party/zlib_v128/gzclose.c \
    $$PWD/third_party/zlib_v128/gzlib.c \
    $$PWD/third_party/zlib_v128/gzread.c \
    $$PWD/third_party/zlib_v128/gzwrite.c \
    $$PWD/third_party/zlib_v128/infback.c \
    $$PWD/third_party/zlib_v128/inffast.c \
    $$PWD/third_party/zlib_v128/inflate.c \
    $$PWD/third_party/zlib_v128/inftrees.c \
    $$PWD/third_party/zlib_v128/trees.c \
    $$PWD/third_party/zlib_v128/uncompr.c \
    $$PWD/third_party/zlib_v128/zutil.c \
    $$PWD/third_party/agg23/agg_curves.cpp \
    $$PWD/third_party/agg23/agg_path_storage.cpp \
    $$PWD/third_party/agg23/agg_rasterizer_scanline_aa.cpp \
    $$PWD/third_party/agg23/agg_vcgen_dash.cpp \
    $$PWD/third_party/agg23/agg_vcgen_stroke.cpp \
    $$PWD/third_party/freetype/src/base/ftbase.c \
    $$PWD/third_party/freetype/src/base/ftbitmap.c \
    $$PWD/third_party/freetype/src/base/ftglyph.c \
    $$PWD/third_party/freetype/src/base/ftinit.c \
    $$PWD/third_party/freetype/src/base/ftlcdfil.c \
    $$PWD/third_party/freetype/src/base/ftmm.c \
    $$PWD/third_party/freetype/src/base/ftsystem.c \
    $$PWD/third_party/freetype/src/cff/cff.c \
    $$PWD/third_party/freetype/src/cid/type1cid.c \
    $$PWD/third_party/freetype/src/psaux/psaux.c \
    $$PWD/third_party/freetype/src/pshinter/pshinter.c \
    $$PWD/third_party/freetype/src/psnames/psmodule.c \
    $$PWD/third_party/freetype/src/raster/raster.c \
    $$PWD/third_party/freetype/src/sfnt/sfnt.c \
    $$PWD/third_party/freetype/src/smooth/smooth.c \
    $$PWD/third_party/freetype/src/truetype/truetype.c \
    $$PWD/third_party/freetype/src/type1/type1.c \
    $$PWD/fpdfsdk/cba_annotiterator.cpp \
    $$PWD/fpdfsdk/cfx_systemhandler.cpp \
    $$PWD/fpdfsdk/cpdfsdk_annot.cpp \
    $$PWD/fpdfsdk/cpdfsdk_annothandlermgr.cpp \
    $$PWD/fpdfsdk/cpdfsdk_annotiterator.cpp \
    $$PWD/fpdfsdk/cpdfsdk_baannot.cpp \
    $$PWD/fpdfsdk/cpdfsdk_baannothandler.cpp \
    $$PWD/fpdfsdk/cpdfsdk_datetime.cpp \
    $$PWD/fpdfsdk/cpdfsdk_formfillenvironment.cpp \
    $$PWD/fpdfsdk/cpdfsdk_interform.cpp \
    $$PWD/fpdfsdk/cpdfsdk_pageview.cpp \
    $$PWD/fpdfsdk/cpdfsdk_widget.cpp \
    $$PWD/fpdfsdk/cpdfsdk_widgethandler.cpp \
    $$PWD/fpdfsdk/fpdf_dataavail.cpp \
    $$PWD/fpdfsdk/fpdf_ext.cpp \
    $$PWD/fpdfsdk/fpdf_flatten.cpp \
    $$PWD/fpdfsdk/fpdf_progressive.cpp \
    $$PWD/fpdfsdk/fpdf_searchex.cpp \
    $$PWD/fpdfsdk/fpdf_sysfontinfo.cpp \
    $$PWD/fpdfsdk/fpdf_transformpage.cpp \
    $$PWD/fpdfsdk/fpdfdoc.cpp \
    $$PWD/fpdfsdk/fpdfeditimg.cpp \
    $$PWD/fpdfsdk/fpdfeditpage.cpp \
    $$PWD/fpdfsdk/fpdfformfill.cpp \
    $$PWD/fpdfsdk/fpdfppo.cpp \
    $$PWD/fpdfsdk/fpdfsave.cpp \
    $$PWD/fpdfsdk/fpdftext.cpp \
    $$PWD/fpdfsdk/fpdfview.cpp \
    $$PWD/fpdfsdk/fsdk_actionhandler.cpp \
    $$PWD/fpdfsdk/fsdk_pauseadapter.cpp \
    $$PWD/fpdfsdk/pdfsdk_fieldaction.cpp \
    $$PWD/core/fdrm/crypto/fx_crypt.cpp \
    $$PWD/core/fdrm/crypto/fx_crypt_aes.cpp \
    $$PWD/core/fdrm/crypto/fx_crypt_sha.cpp \
    $$PWD/core/fpdfdoc/cline.cpp \
    $$PWD/core/fpdfdoc/clines.cpp \
    $$PWD/core/fpdfdoc/cpdf_aaction.cpp \
    $$PWD/core/fpdfdoc/cpdf_action.cpp \
    $$PWD/core/fpdfdoc/cpdf_actionfields.cpp \
    $$PWD/core/fpdfdoc/cpdf_annot.cpp \
    $$PWD/core/fpdfdoc/cpdf_annotlist.cpp \
    $$PWD/core/fpdfdoc/cpdf_apsettings.cpp \
    $$PWD/core/fpdfdoc/cpdf_bookmark.cpp \
    $$PWD/core/fpdfdoc/cpdf_bookmarktree.cpp \
    $$PWD/core/fpdfdoc/cpdf_defaultappearance.cpp \
    $$PWD/core/fpdfdoc/cpdf_dest.cpp \
    $$PWD/core/fpdfdoc/cpdf_docjsactions.cpp \
    $$PWD/core/fpdfdoc/cpdf_filespec.cpp \
    $$PWD/core/fpdfdoc/cpdf_formcontrol.cpp \
    $$PWD/core/fpdfdoc/cpdf_formfield.cpp \
    $$PWD/core/fpdfdoc/cpdf_iconfit.cpp \
    $$PWD/core/fpdfdoc/cpdf_interform.cpp \
    $$PWD/core/fpdfdoc/cpdf_link.cpp \
    $$PWD/core/fpdfdoc/cpdf_linklist.cpp \
    $$PWD/core/fpdfdoc/cpdf_metadata.cpp \
    $$PWD/core/fpdfdoc/cpdf_nametree.cpp \
    $$PWD/core/fpdfdoc/cpdf_numbertree.cpp \
    $$PWD/core/fpdfdoc/cpdf_occontext.cpp \
    $$PWD/core/fpdfdoc/cpdf_pagelabel.cpp \
    $$PWD/core/fpdfdoc/cpdf_variabletext.cpp \
    $$PWD/core/fpdfdoc/cpdf_viewerpreferences.cpp \
    $$PWD/core/fpdfdoc/cpvt_color.cpp \
    $$PWD/core/fpdfdoc/cpvt_fontmap.cpp \
    $$PWD/core/fpdfdoc/cpvt_generateap.cpp \
    $$PWD/core/fpdfdoc/cpvt_sectioninfo.cpp \
    $$PWD/core/fpdfdoc/cpvt_wordinfo.cpp \
    $$PWD/core/fpdfdoc/csection.cpp \
    $$PWD/core/fpdfdoc/ctypeset.cpp \
    $$PWD/core/fpdfdoc/doc_tagged.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/Adobe-CNS1-UCS2_5.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/B5pc-H_0.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/B5pc-V_0.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/CNS-EUC-H_0.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/CNS-EUC-V_0.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/ETen-B5-H_0.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/ETen-B5-V_0.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/ETenms-B5-H_0.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/ETenms-B5-V_0.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/HKscs-B5-H_5.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/HKscs-B5-V_5.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/UniCNS-UCS2-H_3.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/UniCNS-UCS2-V_3.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/UniCNS-UTF16-H_0.cpp \
    $$PWD/core/fpdfapi/cmaps/CNS1/cmaps_cns1.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/Adobe-GB1-UCS2_5.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/GB-EUC-H_0.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/GB-EUC-V_0.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/GBK-EUC-H_2.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/GBK-EUC-V_2.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/GBK2K-H_5.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/GBK2K-V_5.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/GBKp-EUC-H_2.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/GBKp-EUC-V_2.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/GBpc-EUC-H_0.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/GBpc-EUC-V_0.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/UniGB-UCS2-H_4.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/UniGB-UCS2-V_4.cpp \
    $$PWD/core/fpdfapi/cmaps/GB1/cmaps_gb1.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/83pv-RKSJ-H_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/90ms-RKSJ-H_2.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/90ms-RKSJ-V_2.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/90msp-RKSJ-H_2.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/90msp-RKSJ-V_2.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/90pv-RKSJ-H_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/Add-RKSJ-H_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/Add-RKSJ-V_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/Adobe-Japan1-UCS2_4.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/EUC-H_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/EUC-V_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/Ext-RKSJ-H_2.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/Ext-RKSJ-V_2.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/H_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/UniJIS-UCS2-HW-H_4.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/UniJIS-UCS2-HW-V_4.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/UniJIS-UCS2-H_4.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/UniJIS-UCS2-V_4.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/V_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Japan1/cmaps_japan1.cpp \
    $$PWD/core/fpdfapi/cmaps/Korea1/Adobe-Korea1-UCS2_2.cpp \
    $$PWD/core/fpdfapi/cmaps/Korea1/KSC-EUC-H_0.cpp \
    $$PWD/core/fpdfapi/cmaps/Korea1/KSC-EUC-V_0.cpp \
    $$PWD/core/fpdfapi/cmaps/Korea1/KSCms-UHC-HW-H_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Korea1/KSCms-UHC-HW-V_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Korea1/KSCms-UHC-H_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Korea1/KSCms-UHC-V_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Korea1/KSCpc-EUC-H_0.cpp \
    $$PWD/core/fpdfapi/cmaps/Korea1/UniKS-UCS2-H_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Korea1/UniKS-UCS2-V_1.cpp \
    $$PWD/core/fpdfapi/cmaps/Korea1/UniKS-UTF16-H_0.cpp \
    $$PWD/core/fpdfapi/cmaps/Korea1/cmaps_korea1.cpp \
    $$PWD/core/fpdfapi/cmaps/fpdf_cmaps.cpp \
    $$PWD/core/fpdfapi/cpdf_modulemgr.cpp \
    $$PWD/core/fpdfapi/cpdf_pagerendercontext.cpp \
    $$PWD/core/fpdfapi/edit/cpdf_pagecontentgenerator.cpp \
    $$PWD/core/fpdfapi/edit/fpdf_edit_create.cpp \
    $$PWD/core/fpdfapi/font/cpdf_cidfont.cpp \
    $$PWD/core/fpdfapi/font/cpdf_font.cpp \
    $$PWD/core/fpdfapi/font/cpdf_fontencoding.cpp \
    $$PWD/core/fpdfapi/font/cpdf_simplefont.cpp \
    $$PWD/core/fpdfapi/font/cpdf_truetypefont.cpp \
    $$PWD/core/fpdfapi/font/cpdf_type1font.cpp \
    $$PWD/core/fpdfapi/font/cpdf_type3char.cpp \
    $$PWD/core/fpdfapi/font/cpdf_type3font.cpp \
    $$PWD/core/fpdfapi/font/fpdf_font.cpp \
    $$PWD/core/fpdfapi/font/fpdf_font_cid.cpp \
    $$PWD/core/fpdfapi/font/ttgsubtable.cpp \
    $$PWD/core/fpdfapi/page/cpdf_allstates.cpp \
    $$PWD/core/fpdfapi/page/cpdf_clippath.cpp \
    $$PWD/core/fpdfapi/page/cpdf_color.cpp \
    $$PWD/core/fpdfapi/page/cpdf_colorspace.cpp \
    $$PWD/core/fpdfapi/page/cpdf_colorstate.cpp \
    $$PWD/core/fpdfapi/page/cpdf_contentmark.cpp \
    $$PWD/core/fpdfapi/page/cpdf_contentmarkitem.cpp \
    $$PWD/core/fpdfapi/page/cpdf_contentparser.cpp \
    $$PWD/core/fpdfapi/page/cpdf_docpagedata.cpp \
    $$PWD/core/fpdfapi/page/cpdf_form.cpp \
    $$PWD/core/fpdfapi/page/cpdf_formobject.cpp \
    $$PWD/core/fpdfapi/page/cpdf_generalstate.cpp \
    $$PWD/core/fpdfapi/page/cpdf_graphicstates.cpp \
    $$PWD/core/fpdfapi/page/cpdf_image.cpp \
    $$PWD/core/fpdfapi/page/cpdf_imageobject.cpp \
    $$PWD/core/fpdfapi/page/cpdf_meshstream.cpp \
    $$PWD/core/fpdfapi/page/cpdf_page.cpp \
    $$PWD/core/fpdfapi/page/cpdf_pagemodule.cpp \
    $$PWD/core/fpdfapi/page/cpdf_pageobject.cpp \
    $$PWD/core/fpdfapi/page/cpdf_pageobjectholder.cpp \
    $$PWD/core/fpdfapi/page/cpdf_pageobjectlist.cpp \
    $$PWD/core/fpdfapi/page/cpdf_path.cpp \
    $$PWD/core/fpdfapi/page/cpdf_pathobject.cpp \
    $$PWD/core/fpdfapi/page/cpdf_pattern.cpp \
    $$PWD/core/fpdfapi/page/cpdf_shadingobject.cpp \
    $$PWD/core/fpdfapi/page/cpdf_shadingpattern.cpp \
    $$PWD/core/fpdfapi/page/cpdf_streamcontentparser.cpp \
    $$PWD/core/fpdfapi/page/cpdf_streamparser.cpp \
    $$PWD/core/fpdfapi/page/cpdf_textobject.cpp \
    $$PWD/core/fpdfapi/page/cpdf_textstate.cpp \
    $$PWD/core/fpdfapi/page/cpdf_tilingpattern.cpp \
    $$PWD/core/fpdfapi/page/fpdf_page_colors.cpp \
    $$PWD/core/fpdfapi/page/fpdf_page_func.cpp \
    $$PWD/core/fpdfapi/parser/cfdf_document.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_array.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_boolean.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_crypto_handler.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_data_avail.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_dictionary.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_document.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_hint_tables.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_indirect_object_holder.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_linearized_header.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_name.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_null.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_number.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_object.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_parser.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_reference.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_security_handler.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_simple_parser.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_stream.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_stream_acc.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_string.cpp \
    $$PWD/core/fpdfapi/parser/cpdf_syntax_parser.cpp \
    $$PWD/core/fpdfapi/parser/fpdf_parser_decode.cpp \
    $$PWD/core/fpdfapi/parser/fpdf_parser_utility.cpp \
    $$PWD/core/fpdfapi/render/cpdf_docrenderdata.cpp \
    $$PWD/core/fpdfapi/render/cpdf_type3cache.cpp \
    $$PWD/core/fpdfapi/render/cpdf_type3glyphs.cpp \
    $$PWD/core/fpdfapi/render/fpdf_render.cpp \
    $$PWD/core/fpdfapi/render/fpdf_render_cache.cpp \
    $$PWD/core/fpdfapi/render/fpdf_render_image.cpp \
    $$PWD/core/fpdfapi/render/fpdf_render_loadimage.cpp \
    $$PWD/core/fpdfapi/render/fpdf_render_pattern.cpp \
    $$PWD/core/fpdfapi/render/fpdf_render_text.cpp \
    $$PWD/core/fpdftext/cpdf_linkextract.cpp \
    $$PWD/core/fpdftext/cpdf_textpage.cpp \
    $$PWD/core/fpdftext/cpdf_textpagefind.cpp \
    $$PWD/core/fpdftext/unicodenormalizationdata.cpp \
    $$PWD/core/fxcodec/codec/fx_codec.cpp \
    $$PWD/core/fxcodec/codec/fx_codec_fax.cpp \
    $$PWD/core/fxcodec/codec/fx_codec_flate.cpp \
    $$PWD/core/fxcodec/codec/fx_codec_icc.cpp \
    $$PWD/core/fxcodec/codec/fx_codec_jbig.cpp \
    $$PWD/core/fxcodec/codec/fx_codec_jpeg.cpp \
    $$PWD/core/fxcodec/codec/fx_codec_jpx_opj.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_ArithDecoder.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_ArithIntDecoder.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_BitStream.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_Context.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_GrdProc.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_GrrdProc.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_GsidProc.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_HtrdProc.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_HuffmanDecoder.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_HuffmanTable.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_HuffmanTable_Standard.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_Image.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_PatternDict.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_PddProc.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_SddProc.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_Segment.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_SymbolDict.cpp \
    $$PWD/core/fxcodec/jbig2/JBig2_TrdProc.cpp \
    $$PWD/core/fxcrt/fx_basic_array.cpp \
    $$PWD/core/fxcrt/fx_basic_bstring.cpp \
    $$PWD/core/fxcrt/fx_basic_buffer.cpp \
    $$PWD/core/fxcrt/fx_basic_coords.cpp \
    $$PWD/core/fxcrt/fx_basic_gcc.cpp \
    $$PWD/core/fxcrt/fx_basic_list.cpp \
    $$PWD/core/fxcrt/fx_basic_memmgr.cpp \
    $$PWD/core/fxcrt/fx_basic_plex.cpp \
    $$PWD/core/fxcrt/fx_basic_utf.cpp \
    $$PWD/core/fxcrt/fx_basic_util.cpp \
    $$PWD/core/fxcrt/fx_basic_wstring.cpp \
    $$PWD/core/fxcrt/fx_bidi.cpp \
    $$PWD/core/fxcrt/fx_extension.cpp \
    $$PWD/core/fxcrt/fx_ucddata.cpp \
    $$PWD/core/fxcrt/fx_unicode.cpp \
    $$PWD/core/fxcrt/fx_xml_composer.cpp \
    $$PWD/core/fxcrt/fx_xml_parser.cpp \
    $$PWD/core/fxcrt/fxcrt_posix.cpp \
    $$PWD/core/fxcrt/fxcrt_stream.cpp \
    $$PWD/core/fxcrt/fxcrt_windows.cpp \
    $$PWD/core/fxge/dib/fx_dib_composite.cpp \
    $$PWD/core/fxge/dib/fx_dib_convert.cpp \
    $$PWD/core/fxge/dib/fx_dib_engine.cpp \
    $$PWD/core/fxge/dib/fx_dib_main.cpp \
    $$PWD/core/fxge/dib/fx_dib_transform.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitDingbats.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitFixed.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitFixedBold.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitFixedBoldItalic.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitFixedItalic.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitSans.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitSansBold.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitSansBoldItalic.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitSansItalic.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitSansMM.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitSerif.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitSerifBold.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitSerifBoldItalic.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitSerifItalic.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitSerifMM.cpp \
    $$PWD/core/fxge/fontdata/chromefontdata/FoxitSymbol.cpp \
    $$PWD/core/fxge/freetype/fx_freetype.cpp \
    $$PWD/core/fxge/ge/cfx_cliprgn.cpp \
    $$PWD/core/fxge/ge/cfx_facecache.cpp \
    $$PWD/core/fxge/ge/cfx_folderfontinfo.cpp \
    $$PWD/core/fxge/ge/cfx_font.cpp \
    $$PWD/core/fxge/ge/cfx_fontcache.cpp \
    $$PWD/core/fxge/ge/cfx_fontmapper.cpp \
    $$PWD/core/fxge/ge/cfx_fontmgr.cpp \
    $$PWD/core/fxge/ge/cfx_gemodule.cpp \
    $$PWD/core/fxge/ge/cfx_graphstate.cpp \
    $$PWD/core/fxge/ge/cfx_graphstatedata.cpp \
    $$PWD/core/fxge/ge/cfx_pathdata.cpp \
    $$PWD/core/fxge/ge/cfx_renderdevice.cpp \
    $$PWD/core/fxge/ge/cfx_substfont.cpp \
    $$PWD/core/fxge/ge/cfx_unicodeencoding.cpp \
    $$PWD/core/fxge/ge/cttfontdesc.cpp \
    $$PWD/core/fxge/ge/fx_ge_fontmap.cpp \
    $$PWD/core/fxge/ge/fx_ge_linux.cpp \
    $$PWD/core/fxge/ge/fx_ge_text.cpp \
    $$PWD/core/fxge/ifx_renderdevicedriver.cpp \
    $$PWD/core/fxge/agg/fx_agg_driver.cpp \
    $$PWD/fpdfsdk/fxedit/fxet_ap.cpp \
    $$PWD/fpdfsdk/fxedit/fxet_edit.cpp \
    $$PWD/fpdfsdk/fxedit/fxet_list.cpp \
    $$PWD/fpdfsdk/pdfwindow/PWL_Button.cpp \
    $$PWD/fpdfsdk/pdfwindow/PWL_Caret.cpp \
    $$PWD/fpdfsdk/pdfwindow/PWL_ComboBox.cpp \
    $$PWD/fpdfsdk/pdfwindow/PWL_Edit.cpp \
    $$PWD/fpdfsdk/pdfwindow/PWL_EditCtrl.cpp \
    $$PWD/fpdfsdk/pdfwindow/PWL_FontMap.cpp \
    $$PWD/fpdfsdk/pdfwindow/PWL_Icon.cpp \
    $$PWD/fpdfsdk/pdfwindow/PWL_ListBox.cpp \
    $$PWD/fpdfsdk/pdfwindow/PWL_ScrollBar.cpp \
    $$PWD/fpdfsdk/pdfwindow/PWL_SpecialButton.cpp \
    $$PWD/fpdfsdk/pdfwindow/PWL_Utils.cpp \
    $$PWD/fpdfsdk/pdfwindow/PWL_Wnd.cpp \
    $$PWD/fpdfsdk/formfiller/cba_fontmap.cpp \
    $$PWD/fpdfsdk/formfiller/cffl_checkbox.cpp \
    $$PWD/fpdfsdk/formfiller/cffl_combobox.cpp \
    $$PWD/fpdfsdk/formfiller/cffl_formfiller.cpp \
    $$PWD/fpdfsdk/formfiller/cffl_interactiveformfiller.cpp \
    $$PWD/fpdfsdk/formfiller/cffl_listbox.cpp \
    $$PWD/fpdfsdk/formfiller/cffl_pushbutton.cpp \
    $$PWD/fpdfsdk/formfiller/cffl_radiobutton.cpp \
    $$PWD/fpdfsdk/formfiller/cffl_textfield.cpp



FORMS += \

DISTFILES += \
    $$PWD/build_overrides/README.md \
    $$PWD/build_overrides/build.gni \
    $$PWD/build_overrides/gtest.gni \
    $$PWD/build_overrides/pdfium.gni \
    $$PWD/build_overrides/v8.gni \
    $$PWD/core/fxcodec/DEPS \
    $$PWD/core/fxcodec/codec/DEPS \
    $$PWD/core/fxge/agg/DEPS \
    $$PWD/core/fxge/freetype/DEPS \
    $$PWD/core/fxge/ge/DEPS \
    $$PWD/core/fxge/skia/DEPS \
    $$PWD/docs/getting-started.md \
    $$PWD/docs/pdfium-edit-guide.md \
    $$PWD/docs/v8-getting-started.md \
    $$PWD/fpdfsdk/DEPS \
    $$PWD/fpdfsdk/fpdfxfa/DEPS \
    $$PWD/fpdfsdk/javascript/DEPS \
    $$PWD/fxjs/DEPS \
    $$PWD/infra/config/cq.cfg \
    $$PWD/public/DEPS \
    $$PWD/public/README \
    $$PWD/samples/BUILD.gn \
    $$PWD/samples/DEPS \
    $$PWD/skia/BUILD.gn \
    $$PWD/skia/ext/DEPS \
    $$PWD/third_party/BUILD.gn \
    $$PWD/third_party/DEPS \
    $$PWD/third_party/agg23/0000-bug-466.patch \
    $$PWD/third_party/agg23/0001-gcc-warning.patch \
    $$PWD/third_party/agg23/0002-ubsan-error-fixes.patch \
    $$PWD/third_party/agg23/0003-ubsan-render-line-error.patch \
    $$PWD/third_party/agg23/README.pdfium \
    $$PWD/third_party/base/numerics/OWNERS \
    $$PWD/third_party/freetype/0000-include.patch \
    $$PWD/third_party/freetype/FTL.TXT \
    $$PWD/third_party/freetype/README.pdfium \
    $$PWD/third_party/freetype/src/base/Jamfile \
    $$PWD/third_party/freetype/src/cff/Jamfile \
    $$PWD/third_party/freetype/src/cid/Jamfile \
    $$PWD/third_party/freetype/src/psaux/Jamfile \
    $$PWD/third_party/freetype/src/pshinter/Jamfile \
    $$PWD/third_party/freetype/src/psnames/Jamfile \
    $$PWD/third_party/freetype/src/raster/Jamfile \
    $$PWD/third_party/freetype/src/sfnt/Jamfile \
    $$PWD/third_party/freetype/src/smooth/Jamfile \
    $$PWD/third_party/freetype/src/truetype/Jamfile \
    $$PWD/third_party/freetype/src/type1/Jamfile \
    $$PWD/third_party/lcms/0000-cmserr-changes.patch \
    $$PWD/third_party/lcms/0001-fix-include.patch \
    $$PWD/third_party/lcms/0002-old-performance-fix.patch \
    $$PWD/third_party/lcms/0003-old-uninitialized-in-LUTevalFloat.patch \
    $$PWD/third_party/lcms/0004-old-uninitialized-in-LUTeval16.patch \
    $$PWD/third_party/lcms/0005-old-fix-e-with-tilde.patch \
    $$PWD/third_party/lcms/0006-tag-type-confusion.patch \
    $$PWD/third_party/lcms/0008-infinite-loop-GrowNamedColorList.patch \
    $$PWD/third_party/lcms/0009-uninit.patch \
    $$PWD/third_party/lcms/0010-memory-leak-Type_Curve_Read.patch \
    $$PWD/third_party/lcms/0011-memory-leak-AllocEmptyTransform.patch \
    $$PWD/third_party/lcms/0012-memory-leak-Type_NamedColor_Read.patch \
    $$PWD/third_party/lcms/0013-memory-leak-OptimizeByResampling.patch \
    $$PWD/third_party/lcms/0014-memory-leak-Type_MPEmatrix_Read.patch \
    $$PWD/third_party/lcms/0015-cmsStageAllocMatrix-param-swap.patch \
    $$PWD/third_party/lcms/0016-reject-nan.patch \
    $$PWD/third_party/lcms/0017-memory-leak-ReadSegmentedCurve.patch \
    $$PWD/third_party/lcms/0018-backport-c0a98d86.patch \
    $$PWD/third_party/lcms/0019-utf8.patch \
    $$PWD/third_party/lcms/0020-avoid-fixed-inf.patch \
    $$PWD/third_party/lcms/0021-sanitize-float-read.patch \
    $$PWD/third_party/lcms/0022-check-LUT-and-MPE.patch \
    $$PWD/third_party/lcms/0023-upstream-integer-overflow-MPEmatrix_Read.patch \
    $$PWD/third_party/lcms/0024-verify-size-before-reading.patch \
    $$PWD/third_party/lcms/0025-upstream-direct-leak-Type_MPE_Read.patch \
    $$PWD/third_party/lcms/0026-more-unsupported-characters.patch \
    $$PWD/third_party/lcms/0027-changes-from-beginning-of-time.patch \
    $$PWD/third_party/lcms/0028-do-not-quickfloor.patch \
    $$PWD/third_party/lcms/0029-drop-register-keyword.patch \
    $$PWD/third_party/lcms/0030-const-data.patch \
    $$PWD/third_party/lcms/0031-wrong-tag-element-count.patch \
    $$PWD/third_party/lcms/0032-cgats-allocation.patch \
    $$PWD/third_party/lcms/README.pdfium \
    $$PWD/third_party/libopenjpeg20/0000-use-colorspace.patch \
    $$PWD/third_party/libopenjpeg20/0001-image-data.patch \
    $$PWD/third_party/libopenjpeg20/0002-packet-iterator.patch \
    $$PWD/third_party/libopenjpeg20/0003-dwt-decode.patch \
    $$PWD/third_party/libopenjpeg20/0004-j2k_read_mcc.patch \
    $$PWD/third_party/libopenjpeg20/0005-jp2_apply_pclr.patch \
    $$PWD/third_party/libopenjpeg20/0006-tcd_init_tile.patch \
    $$PWD/third_party/libopenjpeg20/0007-jp2_read_cmap.patch \
    $$PWD/third_party/libopenjpeg20/0008-jp2_check_color.patch \
    $$PWD/third_party/libopenjpeg20/0009-opj_pi_next.patch \
    $$PWD/third_party/libopenjpeg20/0010-pi_update_decode_poc.patch \
    $$PWD/third_party/libopenjpeg20/0011-j2k_update_image_data.patch \
    $$PWD/third_party/libopenjpeg20/0012-mct_sse.patch \
    $$PWD/third_party/libopenjpeg20/0013-attrib_fix.patch \
    $$PWD/third_party/libopenjpeg20/0014-opj_jp2_read_ihdr_leak.patch \
    $$PWD/third_party/libopenjpeg20/0015-read_SPCod_SPCoc_overflow.patch \
    $$PWD/third_party/libopenjpeg20/0016-read_SQcd_SQcc_overflow.patch \
    $$PWD/third_party/libopenjpeg20/0017-tcd_init_tile.patch \
    $$PWD/third_party/libopenjpeg20/0018-tcd_get_decoded_tile_size.patch \
    $$PWD/third_party/libopenjpeg20/0019-tcd_init_tile.patch \
    $$PWD/third_party/libopenjpeg20/0020-opj_aligned_malloc.patch \
    $$PWD/third_party/libopenjpeg20/0021-tcd_init_tile_negative.patch \
    $$PWD/third_party/libopenjpeg20/0022-jp2_apply_pclr_overflow.patch \
    $$PWD/third_party/libopenjpeg20/0023-opj_j2k_read_mct_records.patch \
    $$PWD/third_party/libopenjpeg20/CMakeLists.txt \
    $$PWD/third_party/libopenjpeg20/README.pdfium \
    $$PWD/third_party/libopenjpeg20/opj_config.h.cmake.in \
    $$PWD/third_party/libpng16/0000-build-config.patch \
    $$PWD/third_party/libpng16/0002-static-png-gt.patch \
    $$PWD/third_party/libpng16/0003-check-errors-in-set-pcal.patch \
    $$PWD/third_party/libpng16/README.pdfium \
    $$PWD/third_party/libpng16/contrib/intel/INSTALL \
    $$PWD/third_party/libpng16/contrib/intel/intel_sse.patch \
    $$PWD/third_party/libtiff/0000-build-config.patch \
    $$PWD/third_party/libtiff/0001-build-config.patch \
    $$PWD/third_party/libtiff/0002-CVE-2015-8665-8683.patch \
    $$PWD/third_party/libtiff/0003-CVE-2015-8781-8782-8783.patch \
    $$PWD/third_party/libtiff/0004-CVE-2015-8784.patch \
    $$PWD/third_party/libtiff/0005-Leak-TIFFFetchStripThing.patch \
    $$PWD/third_party/libtiff/0006-HeapBufferOverflow-ChopUpSingleUncompressedStrip.patch \
    $$PWD/third_party/libtiff/0007-uninitialized-value.patch \
    $$PWD/third_party/libtiff/0008-HeapBufferOverflow-ChopUpSingleUncompressedStrip.patch \
    $$PWD/third_party/libtiff/0009-HeapBufferOverflow-PixarLogDecode.patch \
    $$PWD/third_party/libtiff/README.pdfium \
    $$PWD/third_party/pymock/LICENSE.txt \
    $$PWD/third_party/pymock/OWNERS \
    $$PWD/third_party/pymock/README.chromium \
    $$PWD/third_party/pymock/mock.py \
    $$PWD/xfa/DEPS \
    $$PWD/xfa/fgas/font/DEPS \
    $$PWD/xfa/fxbarcode/DEPS \
    $$PWD/xfa/fxfa/DEPS \
    $$PWD/xfa/fxfa/app/DEPS

